/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Estudiante;
import Clases.Tutor;
import Clases.Validaciones;
import Metodos.Conexion;
import Metodos.EstudianteDao;
import Metodos.NewHibernateUtil;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import java.util.regex.Pattern;
import javafx.scene.control.cell.ComboBoxListCell;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import net.sf.ehcache.hibernate.HibernateUtil;
import org.hibernate.Criteria;
import org.hibernate.Session;

/**
 *
 *
 */
public class FrmEstudiante extends javax.swing.JFrame {

    //Inicializa la clase donde tengo los metodos para vaildar cada una de las cajas de texto
    Validaciones va = new Validaciones();
    //Instancia la clase conexion
    Conexion conecta = new Conexion();
    //Instancia el metodo para iniciar la conexion con la base
    Connection cn = conecta.getConexion();

    public FrmEstudiante() {
        initComponents();
        this.setLocationRelativeTo(this);
        txtidtu.setVisible(false);
        txtco.setVisible(false);
        llenarCombo();
        va.ValiNumeros(txtcod);
        va.Espacios(txtcod, 5);
        va.ValiLetras(txtnom);
        va.Espacios(txtnom, 30);
        va.ValiLetras(txtest);
        va.Espacios(txtest, 15);
        va.ValiNumeros(txttele);
        va.Espacios(txttele, 10);
        va.Espacios(txtdire, 50);
    }

    //Metodo que lista en un combo box los tutores registrados
    public void llenarCombo() {
        Session sesion = null;
        try {
            sesion = NewHibernateUtil.getSessionFactory().openSession();
            Criteria crit = sesion.createCriteria(Tutor.class);
            List<Tutor> resulset = crit.list();
            cbtu.removeAllItems();
            for (Tutor tu : resulset) {
                cbtu.addItem("" + tu.getNombre());
                //txtidtu.setText(""+tu.getCodigo());       
                //txtidtu.setText(""+tu.getCodigo());
            }
            sesion.close();
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtema = new javax.swing.JTextField();
        txtest = new javax.swing.JTextField();
        txttele = new javax.swing.JTextField();
        txtdire = new javax.swing.JTextField();
        cbtu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        txtco = new javax.swing.JTextField();
        txtidtu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 60, -1));
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 240, -1));
        getContentPane().add(txtema, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 240, -1));
        getContentPane().add(txtest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 240, -1));
        getContentPane().add(txttele, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 240, -1));
        getContentPane().add(txtdire, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, -1));

        cbtu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbtuItemStateChanged(evt);
            }
        });
        cbtu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbtuMouseClicked(evt);
            }
        });
        getContentPane().add(cbtu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direccion:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tutor:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono eliminar.png"))); // NOI18N
        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono guardar.png"))); // NOI18N
        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono salir.png"))); // NOI18N
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        btConsultar.setText("jButton4");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 40, -1));
        getContentPane().add(txtco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 20, -1));
        getContentPane().add(txtidtu, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 70, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            //Verifica que las cajas de texto no esten vacias
            if (txtcod.getText().equals("")
                    || txtnom.getText().equals("")
                    || txtema.getText().equals("")
                    || txtest.getText().equals("")
                    || txttele.getText().equals("")
                    || txtdire.getText().equals("")) {
                //Si las cajas de texto estan vacias muestra el mensaje
                JOptionPane.showMessageDialog(null, "LLenar campos vacios");
            } else {
                //Se les da una variable a cada una de las cajas de texto
                int codigo;
                String nombre;
                String direccion;
                String telefono;
                String email;
                String estado;
                String tutor;
                codigo = Integer.parseInt(txtcod.getText());
                nombre = txtnom.getText();
                direccion = txtdire.getText();
                telefono = txttele.getText();
                email = txtema.getText();
                estado = txtest.getText();
                //tutor = cbtu.getSelectedItem().toString();
                tutor = txtidtu.getText();
                //Se instancia la clase y se le envia las variable de la caja de texto
                Estudiante estudiante = new Estudiante(codigo, nombre, direccion, telefono, email, estado, tutor);
                //Una condicion que verifica que no se guarde un registro con el numero 0
                if (txtcod.getText().equals("0")) {
                    JOptionPane.showMessageDialog(null, "No se puede guardar registro con 0");
                    vaciar();
                } else {
                    //Una condicion que valida el imail
                    if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", txtema.getText()))) {
                        JOptionPane.showMessageDialog(null, "Direccion del Email invalido", "Ingrese uno valido", JOptionPane.ERROR_MESSAGE);
                        txtema.setText("");
                    } else {
                        //Inicializa la clase donde esta el metodo guardar
                        EstudianteDao estudiantedao = new EstudianteDao();
                        //Ejecuta el metodo guardar y manda el objeto que tiene las variables de las caja de texto
                        estudiantedao.Guardar(estudiante);
                        //Muestra mensaje cuando se cumplio el metodo sin presentar ningun error
                        JOptionPane.showMessageDialog(null, "Grabado Exitoso");
                        //Llama el metodo de vaciar
                        vaciar();
                    }
                }
            }
        } catch (Exception e) {
            //Mensaje de error si no se ejecuta la funcion
            JOptionPane.showMessageDialog(null, "Error al guardar" + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int id;
            //Lee de id ingresado en la caja de texto y lo pone en una variable
            id = Integer.parseInt(txtcod.getText());
            EstudianteDao estudiantedao = new EstudianteDao();
            Estudiante estudiante = null;
            //Le manda el id al meodo para poderlo eliminar
            estudiante = estudiantedao.obtenerEstudiante(id);
            //Ejecuta el metodo de eliminar
            estudiantedao.Eliminar(estudiante);
            JOptionPane.showMessageDialog(null, "Borrado Exitoso");
            //Ejecuta el metodo para vaciar las cajas de texto
            vaciar();
        } catch (Exception e) {
            //Muestra el mensaje de excepcion cuando no se cumple la funcion
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Llama a la otra ventana
        FrmRegistro mn = new FrmRegistro();
        //La hace visible
        mn.setVisible(true);
        //El dispose permite que se cierre la ventana y se abra la otra
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbtuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtuMouseClicked
        // TODO add your handling code here:
        String ciu = cbtu.getSelectedItem().toString();
        //Se le da una variable a ;a caja de texto
        String nom = txtidtu.getText();
        //Se 
        String sql = "SELECT nombre FROM tutor WHERE codigo=1";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtidtu.setText(rs.getString(1));
            }
            nom = txtidtu.getText();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_cbtuMouseClicked

    private void cbtuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbtuItemStateChanged
        // TODO add your handling code here:
        //Se le da una variable al combo box
        String ciu = cbtu.getSelectedItem().toString();
        //Se hace la consulta y se llama ala variable donde pusimos el combo box
        String sql = "SELECT codigo FROM tutor WHERE nombre = '" + ciu + "'";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                //Me devuelve el id del tutor
                txtidtu.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, ex.getMessage(),"Warning",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cbtuItemStateChanged

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        // TODO add your handling code here:
        String cod = txtcod.getText();
        //Condicion que verifica si la caja de texto esta vacia
        if (txtcod.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Caja Vacia Ingrese valor");
        } else {
            //Ejecuta instacia Sql que hace la consulta en la bd por medio de la variale 
            //donde pusimos la caja de texto que queremos consultar
            String sql = "SELECT nombre, direccion, email, telefono, estado, codigo FROM estudiante WHERE codigo = '" + cod + "'";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    txtnom.setText(rs.getString(1));
                    txtdire.setText(rs.getString(2));
                    txttele.setText(rs.getString(3));
                    txtema.setText(rs.getString(4));
                    txtest.setText(rs.getString(5));
                    txtco.setText(rs.getString(6));
                    //cbtu.setSelectedItem(rs.getString(6).toString());
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                //JOptionPane.showMessageDialog(null,"Campo Vacio");
            }
            //Esta condicion verifica si el codigo ingresado es igual a uno que esta registrado en la base 
            if (txtcod.getText().equals(txtco.getText())) {

            } else {
                //Muestra mensaje que no se encontro tutor y vacia la caja de texto
                JOptionPane.showMessageDialog(null, "Estudiante no encontrado");
                txtcod.setText(null);
            }
        }

    }//GEN-LAST:event_btConsultarActionPerformed

    //Metodo que vacia las cajas de texto
    void vaciar() {
        txtcod.setText("");
        txtdire.setText("");
        txtema.setText("");
        txtest.setText("");
        txtnom.setText("");
        txttele.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JComboBox<String> cbtu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtco;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdire;
    private javax.swing.JTextField txtema;
    private javax.swing.JTextField txtest;
    public static javax.swing.JTextField txtidtu;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttele;
    // End of variables declaration//GEN-END:variables
}
