/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Tutor;
import Clases.Validaciones;
import Metodos.Conexion;
import Metodos.TutorDao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 *
 */
public class FrmTutor extends javax.swing.JFrame {

    //Inicializa la clase donde tengo los metodos para vaildar cada una de las cajas de texto
    Validaciones va = new Validaciones();
    //Instancia la clase conexion 
    Conexion conecta = new Conexion();
    //Instancia el metodo para iniciar la conexion con la base
    Connection cn = conecta.getConexion();

    /**
     * Creates new form FrmTutor
     */
    public FrmTutor() {
        initComponents();
        this.setLocationRelativeTo(this);
        txtco.setVisible(false);
        va.ValiNumeros(txtcod);
        va.Espacios(txtcod, 5);
        va.ValiLetras(txtnom);
        va.Espacios(txtnom, 30);
        va.ValiLetras(txtest);
        va.Espacios(txtest, 15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtcod = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtema = new javax.swing.JTextField();
        txtest = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtco = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono guardar.png"))); // NOI18N
        jButton1.setText("Grabar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono eliminar.png"))); // NOI18N
        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 60, -1));
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, -1));
        getContentPane().add(txtema, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, -1));
        getContentPane().add(txtest, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono salir.png"))); // NOI18N
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));
        getContentPane().add(txtco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 30, -1));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 505, 383));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //Verifica que las cajas de texto no esten vacias
            if (txtcod.getText().equals("")
                    || txtnom.getText().equals("")
                    || txtema.getText().equals("")
                    || txtest.getText().equals("")) {
                //Si las cajas de texto estan vacias muestra el mensaje
                JOptionPane.showMessageDialog(null, "LLenar campos vacios");
            } else {
                //Se les da una variable a cada una de las cajas de texto
                int codigo;
                String nombre;
                String email;
                String estado;
                codigo = Integer.parseInt(txtcod.getText());
                nombre = txtnom.getText();
                email = txtema.getText();
                estado = txtest.getText();
                //Se instancia la clase y se le envia las variable de la caja de texto
                Tutor tutor = new Tutor(codigo, nombre, email, estado);
                //Una condicion que verifica que no se guarde un registro con el numero 0
                if (txtcod.getText().equals("0")) {
                    JOptionPane.showMessageDialog(null, "No se puede guardar registro con 0");
                    vaciar();
                } else {
                    //Una condicion que valida el imail
                    if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", txtema.getText()))) {
                        JOptionPane.showMessageDialog(null, "Direccion del Email invalido", "Ingrese uno valido", JOptionPane.ERROR_MESSAGE);
                        txtema.setText("");
                    } else {
                        //Inicializa la clase donde esta el metodo guardar
                        TutorDao tutordao = new TutorDao();
                        //Ejecuta el metodo guardar y manda el objeto que tiene las variables de las caja de texto
                        tutordao.Guardar(tutor);
                        //Muestra mensaje cuando se cumplio el metodo sin presentar ningun error
                        JOptionPane.showMessageDialog(null, "Grabado Exitoso");
                        //Llama el metodo de vaciar
                        vaciar();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al guardar" + e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            int id;
            //Lee de id ingresado en la caja de texto y lo pone en una variable
            id = Integer.parseInt(txtcod.getText());
            //Instancia la clase donde esta metodo para poder eliminarlo
            TutorDao tutordao = new TutorDao();
            Tutor tutor = null;
            //Le manda el id al meodo para poderlo eliminar
            tutor = tutordao.obtenerTutor(id);
            //Ejecuta el metodo de eliminar
            tutordao.Eliminar(tutor);
            JOptionPane.showMessageDialog(null, "Borrado Exitoso");
            //Ejecuta el metodo para vaciar las cajas de texto
            vaciar();
        } catch (Exception e) {
            //Muestra el mensaje de excepcion cuando no se cumple la funcion
            JOptionPane.showMessageDialog(null, "Error" + e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FrmRegistro mn = new FrmRegistro();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String cod = txtcod.getText();
        if (txtcod.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Caja Vacia");
        } else {
            //Consulta el tutor por el codigo 
            String sql = "SELECT nombre, email, estado, codigo FROM tutor WHERE codigo = '" + cod + "'";
            try {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    //devuelve los datos registrados en la base
                    txtnom.setText(rs.getString(1));
                    txtema.setText(rs.getString(2));
                    txtest.setText(rs.getString(3));
                    txtco.setText(rs.getString(4));
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
                //JOptionPane.showMessageDialog(null,"Campo Vacio"+e);
            }
            //Esta condicion verifica si el codigo ingresado es igual a uno que esta registrado en la base 
            if (txtcod.getText().equals(txtco.getText())) {

            } else {
                //Muestra mensaje que no se encontro tutor y vacia la caja de texto
                JOptionPane.showMessageDialog(null, "Tutor no encontrado");
                txtcod.setText(null);
            }

        }


    }//GEN-LAST:event_jButton4ActionPerformed

    //Metodo para vaciar las cajas de texto
    void vaciar() {
        txtcod.setText("");
        txtema.setText("");
        txtest.setText("");
        txtnom.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtco;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtema;
    private javax.swing.JTextField txtest;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
