package Clases;
// Generated 23/06/2019 11:57:19 AM by Hibernate Tools 4.3.1



/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


    //atributos de la clase
     private int codigo;
     private String nombre;
     private String email;
     private String estado;

     //constructor vacio
    public Tutor() {
    }

	
    public Tutor(int codigo) {
        this.codigo = codigo;
    }
    
    //constructor con los atributos
    public Tutor(int codigo, String nombre, String email, String estado) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.email = email;
       this.estado = estado;
    }
   
    //metodos set y get de mis atributos
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


